/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import controller.AbrirRequisicaoController;
import controller.CadastrarMesaController;
import controller.CadastrarProdutoController;
import controller.FazerPedidoController;
import controller.ListarPesquisarRequisicaoController;
import dao.RequisicoesDAO;
import exception.FormatoInvalidoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author imcat
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        RequisicoesDAO requisicoes = RequisicoesDAO.getInstance();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        btnAbrirRequisicao = new javax.swing.JButton();
        btnPesquisarRequisicao = new javax.swing.JButton();
        btnCadProduto = new javax.swing.JButton();
        btnAbrirPedido = new javax.swing.JButton();
        btnCadMesa = new javax.swing.JButton();
        btnCadCliente = new javax.swing.JButton();
        btnListarProdutos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 248, 226));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Menu");

        btnAbrirRequisicao.setText("Abrir Requisição");
        btnAbrirRequisicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAbrirRequisicaoMouseClicked(evt);
            }
        });
        btnAbrirRequisicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirRequisicaoActionPerformed(evt);
            }
        });
        getContentPane().add(abrirRequisicaoBtn1, java.awt.BorderLayout.CENTER);

        btnPesquisarRequisicao.setText("Pesquisar Requisicao");
        btnPesquisarRequisicao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarRequisicaoMouseClicked(evt);
            }
        });
        btnPesquisarRequisicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarRequisicaoActionPerformed(evt);
            }
        });

        btnCadProduto.setText("Cadastrar Produto");
        btnCadProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadProdutoMouseClicked(evt);
            }
        });

        btnAbrirPedido.setText("Abrir Pedido");
        btnAbrirPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAbrirPedidoMouseClicked(evt);
            }
        });

        btnCadMesa.setText("Cadastrar Mesa");
        btnCadMesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadMesaMouseClicked(evt);
            }
        });

        btnCadCliente.setText("Cadastrar Cliente");

        btnListarProdutos.setText("Listar Produtos");
        btnListarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarProdutosActionPerformed(evt);
            }
        });

        jMenu1.setText("Mesas");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Requisicoes");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Produtos");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPesquisarRequisicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAbrirRequisicao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCadCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAbrirPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCadMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListarProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAbrirRequisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisarRequisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAbrirPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirRequisicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirRequisicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbrirRequisicaoActionPerformed

    private void btnPesquisarRequisicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarRequisicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarRequisicaoActionPerformed

    private void btnAbrirRequisicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirRequisicaoMouseClicked
        new AbrirRequisicaoController();
    }//GEN-LAST:event_btnAbrirRequisicaoMouseClicked

    private void btnPesquisarRequisicaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarRequisicaoMouseClicked
        try {
            new ListarPesquisarRequisicaoController();
        } catch (FormatoInvalidoException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPesquisarRequisicaoMouseClicked

    private void btnCadProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadProdutoMouseClicked
        new CadastrarProdutoController();
    }//GEN-LAST:event_btnCadProdutoMouseClicked

    private void btnCadMesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadMesaMouseClicked
        new CadastrarMesaController();
    }//GEN-LAST:event_btnCadMesaMouseClicked

    private void btnAbrirPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirPedidoMouseClicked
        try {
            new ListarPesquisarRequisicaoController();
        } catch (FormatoInvalidoException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAbrirPedidoMouseClicked

    private void btnListarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarProdutosActionPerformed

    private void cadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarProdutoActionPerformed
        new CadastrarProdutoController();
    }//GEN-LAST:event_cadastrarProdutoActionPerformed

    private void fazerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fazerPedidoActionPerformed
        new FazerPedidoController();
    }//GEN-LAST:event_fazerPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD
    private javax.swing.JButton btnAbrirPedido;
    private javax.swing.JButton btnAbrirRequisicao;
    private javax.swing.JButton btnCadCliente;
    private javax.swing.JButton btnCadMesa;
    private javax.swing.JButton btnCadProduto;
    private javax.swing.JButton btnListarProdutos;
    private javax.swing.JButton btnPesquisarRequisicao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
=======
    private javax.swing.JButton abrirRequisicaoBtn1;
    private javax.swing.JButton cadastrarProduto;
    private javax.swing.JButton fazerPedido;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton verMesas;
>>>>>>> 740a97e45395c8d79a2cfa1576af6cb22487660f
    // End of variables declaration//GEN-END:variables
}
